### ISSUE TITLE
"Show User Profile" Not Working

### ISSUE THREAD

**Issue by magikalbunny** [milbits/oldcord#26]
When I go to somebody's DMs the "Show User Profile" thing isn't positioned correctly and it looks weird. Profile pictures, statuses, and pronouns are out of place. 
![Capture](https://github.com/milbits/oldcord/assets/85538604/7515e722-7e6d-47b5-8b0b-d29eea127945)

**Comment by milbits** [comment]
sorry i always forget that this screen exists, today i'll really fix it though!

**Comment by KingGamingYT** [comment]
we are so back (still workin on it)
![image](https://github.com/user-attachments/assets/3faf31c2-e9b4-4e7c-b719-b148407dd899)

**Comment by KingGamingYT** [comment]
I agree

currently hung up on the about me and member since text (can't get the originals to hide)  + the note box which comes with all the same positioning issues that exist in the popout except worse because this covers the entire screen and some people have a lot of profile info while others don't
![image](https://github.com/user-attachments/assets/e7ac332e-ff60-41ea-830f-2d7010ecaeaa)

**Comment by KingGamingYT** [comment]
guys will see this and say hell yeah (ignore the blank area at the bottom the buttons just don't load on some profiles because discord is terrible)
![image](https://github.com/user-attachments/assets/e087e863-b0d0-4f72-b1c4-3b99b9f8e158)

**Comment by KingGamingYT** [comment]
discord hasn't broken it again yet so this can be closed, I think
